[[language]]
name = "zig"
file-types = ["zig", "zon"]

[language-server.ruff]
command = "ruff-lsp"

[[language]]
name = "python"
language-servers = [ "ruff" ]
auto-format = true

[[language]]
name = "protobuf"
formatter = { command = "clang-format" }
file-types = ["proto"]
auto-format = true
